# Generated by Django 4.1.7 on 2023-02-20 23:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shaft", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Materials",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("SAE_Number", models.CharField(max_length=64)),
                ("tegangan_tarik", models.FloatField()),
                ("tegangan_luluh", models.FloatField()),
            ],
        ),
    ]
